// TEMPORARY DATA

export let role = "admin";

export const teachersData = [
  {
    id: 1,
    teacherId: "1234567890",
    name: "Youmna Mustafa",
    email: "Youmna@gmail.com",
    photo:
      "https://w7.pngwing.com/pngs/4/736/png-transparent-female-avatar-girl-face-woman-user-flat-classy-users-icon.png",
    phone: "1234567890",
    subjects: ["Math", "Arabic"],
    classes: ["1B", "2A", "3C"],
    address: "Cairo, Nasr City",
  },
  {
    id: 2,
    teacherId: "1234567890",
    name: "Mustafa Hassan",
    email: "Mustafa@gmail.com",
    photo:"https://static.vecteezy.com/system/resources/previews/011/675/382/original/man-avatar-image-for-profile-png.png",
    phone: "1234567890",
    subjects: ["Physics", "Chemistry"],
    classes: ["5A", "4B", "3C"],
    address: "Giza",
  },
  {
    id: 3,
    teacherId: "1234567890",
    name: "Salma Gamal",
    email: "Salma@gmaill.com",
    photo:"https://static.vecteezy.com/system/resources/previews/019/896/012/non_2x/female-user-avatar-icon-in-flat-design-style-person-signs-illustration-png.png",
    phone: "1234567890",
    subjects: ["Biology"],
    classes: ["5A", "4B", "3C"],
    address: "Alexandria ",
  },
  {
    id: 4,
    teacherId: "1234567890",
    name: "Ali Mohamed",
    email: "Ali@gmail.com",
    photo:
      "https://cdn3.iconfinder.com/data/icons/web-design-and-development-2-6/512/87-1024.png",
    phone: "1234567890",
    subjects: ["History"],
    classes: ["5A", "4B", "3C"],
    address: "123 Main St, Cairo",
  },
  {
    id: 5,
    teacherId: "1234567890",
    name: "Nouh Omar",
    email: "Nouh@gmail.com",
    photo:
      "https://static.vecteezy.com/system/resources/previews/014/194/232/original/avatar-icon-human-a-person-s-badge-social-media-profile-symbol-the-symbol-of-a-person-vector.jpg",
    phone: "1234567890",
    subjects: ["Music", "History"],
    classes: ["5A", "4B", "3C"],
    address: "878 Main St, cairo",
  },
  {
    id: 6,
    teacherId: "1234567890",
    name: "Menna sobhy",
    email: "Menna@gmail.com",
    photo:
      "https://static.vecteezy.com/system/resources/previews/009/380/330/original/woman-face-expression-clipart-design-illustration-free-png.png",
    phone: "1234567890",
    subjects: ["Physics"],
    classes: ["5A", "4B", "3C"],
    address: "Giza",
  },
  {
    id: 7,
    teacherId: "1234567890",
    name: "Alaa Adel",
    email: "alaa@black.com",
    photo:
      "https://static.vecteezy.com/system/resources/previews/012/941/847/original/illustration-of-avatar-girl-nice-smiling-woman-with-black-hair-flat-icon-on-purple-background-vector.jpg",
    phone: "1234567890",
    subjects: ["English", "Spanish"],
    classes: ["5A", "4B", "3C"],
    address: "351 Main St,  Cairo",
  },
  {
    id: 8,
    teacherId: "1234567890",
    name: "Mahmoud Ali",
    email: "Mahmoud@gmail.com",
    photo:
      "https://static.vecteezy.com/system/resources/previews/010/967/316/original/avatar-bearded-man-free-vector.jpg",
    phone: "1234567890",
    subjects: ["Math", "Geometry"],
    classes: ["5A", "4B", "3C"],
    address: "824 Main St, Cairo",
  },
  {
    id: 9,
    teacherId: "1234567890",
    name: "Laila Ahmed",
    email: "Laila@gmail.com",
    photo:
      "https://www.premadegraphics.com/img_1/23/Female-Avatar-3.png",
    phone: "1234567890",
    subjects: ["Literature", "English"],
    classes: ["5A", "4B", "3C"],
    address: "Cairo , Nasr City",
  },
  {
    id: 10,
    teacherId: "1234567890",
    name: "Ahmed Ali",
    email: "Ahmed@gmail.com",
    photo:"https://static.vecteezy.com/system/resources/previews/011/459/666/original/people-avatar-icon-png.png",
    phone: "1234567890",
    subjects: ["Biology"],
    classes: ["5A", "4B", "3C"],
    address: "Giza",
  },
];

export const studentsData = [
  {
    id: 1,
    studentId: "1234567890",
    name: "Hassan Mustafa",
    email: "Hassan@gmail.com",
    photo:
      "https://img.freepik.com/premium-vector/student-avatar-icon-set-education_804788-213300.jpg?w=2000",
    phone: "1234567890",
    grade: 5,
    class: "1B",
    address: "124 Main street , cairo",
  },
  {
    id: 2,
    studentId: "1234567890",
    name: "Haneen Wael",
    email: "Haneen@gmail.com",
    photo:
      "https://thumbs.dreamstime.com/b/smiling-cartoon-female-student-avatar-purple-hair-glasses-generative-ai-stylized-d-portrays-young-round-pink-backpack-311377781.jpg",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "178 Main Steet , Giza",
  },
  {
    id: 3,
    studentId: "1234567890",
    name: "Ahmed Saad",
    email: "Ahmed@gmail.com",
    photo:
      "https://static.vecteezy.com/system/resources/previews/021/770/058/non_2x/avatar-of-a-student-character-free-vector.jpg",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "878 Main St, Cairo",
  },
  {
    id: 4,
    studentId: "1234567890",
    name: "Omar Gamal",
    email: "Omar@gmail.com",
    photo:
      "https://static.vecteezy.com/system/resources/previews/012/941/843/non_2x/illustration-of-boy-avatar-student-s-character-face-vector.jpg",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "123 Main St, Cairo",
  },
  {
    id: 5,
    studentId: "1234567890",
    name: "Sara Omar",
    email: "Sara@gmail.com",
    photo:
      "https://static.vecteezy.com/system/resources/previews/021/770/059/original/avatar-of-a-student-character-free-vector.jpg",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "951 Main St, Cairo",
  },
  {
    id: 6,
    studentId: "1234567890",
    name: "Raghad Mohammed",
    email: "Raghad@gmail.com",
    photo:
      "https://tse2.mm.bing.net/th/id/OIP.a9dJTAO-wB3VDOqE0NB8jQAAAA?pid=Api&P=0&h=220",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "127 Main St, Cairo",
  },
  {
    id: 7,
    studentId: "1234567890",
    name: "Omnia Salah",
    email: "Omnia@gmial.com",
    photo:
      "https://cdn2.iconfinder.com/data/icons/circle-avatars-1/128/050_girl_avatar_profile_woman_suit_student_officer-512.png",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "123 Main St, Cairo",
  },
  {
    id: 8,
    studentId: "1234567890",
    name: "Khadija Assem",
    email: "Khadija@gmail.com",
    photo:
      "https://cdn0.iconfinder.com/data/icons/education-and-school-filled-outline-1/128/Primary_school_student_study_school_girl_avatar_child-1024.png",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "123 Main St, Cairo",
  },
  {
    id: 9,
    studentId: "1234567890",
    name: "Youssef Ali",
    email: "Youssef@gmail.com",
    photo:
      "https://img.freepik.com/premium-psd/student-model-avatar-isolated-transparent_59286-6792.jpg?w=2000",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "369 Main St, Cairo",
  },
  {
    id: 10,
    studentId: "1234567890",
    name: "Hesham Tarek",
    email: "Hesham@gmail.com",
    photo:
      "https://static.vecteezy.com/system/resources/previews/021/770/051/large_2x/avatar-of-a-japanese-high-school-character-free-vector.jpg",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "684 Main St, Cairo",
  },
];

export const parentsData = [
  {
    id: 1,
    name: "Ayman Ali",
    students: ["Sarah Ayman"],
    email: "Ayman@gmail.com",
    phone: "1234567890",
    address: "113 Main St, Cairo",
  },
  {
    id: 2,
    name: "Menna Hany",
    students: ["Mariam Hatem"],
    email: "Menna@gmail.com",
    phone: "1234567890",
    address: "15 Main St, Cairo",
  },
  {
    id: 3,
    name: "Omar Fawzy",
    students: ["Areej Omar"],
    email: "Omar@gmail.com",
    phone: "1234567890",
    address: "545 Main St, Cairo",
  },
  {
    id: 4,
    name: "Yazan Mohammed",
    students: ["Ali Yazan", "Farida Yazan"],
    email: "Yazan@gmail.com",
    phone: "1234567890",
    address: "323 Main St, Cairo",
  },
  {
    id: 5,
    name: "Hana Mahmoud",
    students: ["Farid Mostafa"],
    email: "Hana@gmail.com",
    phone: "1234567890",
    address: "242 Main St, Cairo",
  },
  {
    id: 6,
    name: "Amira Hamdy",
    students: ["Reda Tarek"],
    email: "Amira@geller.com",
    phone: "1234567890",
    address: "486 Main St, Cairo",
  },
  {
    id: 7,
    name: "Ahmed Alaa",
    students: ["Hamza Ahmed", "Lilly Ahmed"],
    email: "Ahmed@gmail.com",
    phone: "1234567890",
    address: "75 Main St, Cairo",
  },
  {
    id: 8,
    name: "Anas Gamal",
    students: ["Karim Anas"],
    email: "Anas@gmail.com",
    phone: "1234567890",
    address: "878 Main St, Cairo",
  },
  {
    id: 9,
    name: "Sameh Fahim",
    students: ["suzan Sameh", "Murad Sameh"],
    email: "Sameh@gmail.com",
    phone: "1234567890",
    address: "45 Main St, Cairo",
  },
  {
    id: 10,
    name: "Donia Zahed",
    students: ["Doha Ramzy"],
    email: "Donia@gmail.com",
    phone: "1234567890",
    address: "852 Main St, Cairo",
  },
];

export const subjectsData = [
  {
    id: 1,
    name: "Math",
    teachers: ["Fatma Ahmed", "Zeinb Mohammed"],
  },
  {
    id: 2,
    name: "English",
    teachers: ["Murad Nasr", "Dalia Hady"],
  },
  {
    id: 3,
    name: "Physics",
    teachers: ["Ahmed Omar", "Laila Abdullah"],
  },
  {
    id: 4,
    name: "Chemistry",
    teachers: ["Khaled Tameem", "Noha Rashed"],
  },
  {
    id: 5,
    name: "Biology",
    teachers: ["Aliaa Mohsen", "Lina Saeed"],
  },
  {
    id: 6,
    name: "History",
    teachers: ["Hannah Montaser", "Ibrahim Mohsen"],
  },
  {
    id: 7,
    name: "Geography",
    teachers: ["Lara Emad", "Soha Ali"],
  },
  {
    id: 8,
    name: "Art",
    teachers: ["Badr Mustafa", "Mariam Alaa"],
  },
  {
    id: 9,
    name: "Music",
    teachers: ["Jana Sameh", "Mohammed Atef"],
  },
  {
    id: 10,
    name: "Literature",
    teachers: ["Waled Elbana", "Arwa Amr"],
  },
];

export const classesData = [
  {
    id: 1,
    name: "1A",
    capacity: 20,
    grade: 1,
    supervisor: "Nasr Ali",
  },
  {
    id: 2,
    name: "2B",
    capacity: 22,
    grade: 2,
    supervisor: "Ahmed Nasr",
  },
  {
    id: 3,
    name: "3C",
    capacity: 20,
    grade: 3,
    supervisor: "Tasneem Bassam",
  },
  {
    id: 4,
    name: "4B",
    capacity: 18,
    grade: 4,
    supervisor: "Dima Mohammed",
  },
  {
    id: 5,
    name: "5A",
    capacity: 16,
    grade: 5,
    supervisor: "Idrees Ali",
  },
  {
    id: 5,
    name: "5B",
    capacity: 20,
    grade: 5,
    supervisor: "Leila Ahmed",
  },
  {
    id: 7,
    name: "7A",
    capacity: 18,
    grade: 7,
    supervisor: "Wael Mohammed",
  },
  {
    id: 8,
    name: "6B",
    capacity: 22,
    grade: 6,
    supervisor: "Farid Khaled",
  },
  {
    id: 9,
    name: "6C",
    capacity: 18,
    grade: 6,
    supervisor: "Dawood Omar",
  },
  {
    id: 10,
    name: "6D",
    capacity: 20,
    grade: 6,
    supervisor: "Nesreen Shaker",
  },
];

export const lessonsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "Tamer Ali",
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "Rola Foad",
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "Lobna Gamal",
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "Hania Mosa",
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "Salah Ahmed",
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "Younis Hatem",
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "Haron Saad  ",
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "Lareen Hany",
  },
  {
    id: 9,
    subject: "Physics",
    class: "6C",
    teacher: "Maram Reda",
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "4B",
    teacher: "Batool Adel",
  },
];

export const examsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "Mariam Hossam",
    date: "2026-02-07",
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "Rabab Ahmed",
    date: "2026-02-08",
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "Manal Sayed",
    date: "2026-02-09",
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "Alaa Adel",
    date: "2026-02-10",
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "Amin Fawzy",
    date: "2026-02-11",
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "Dalia Saeed",
    date: "2026-02-12",
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "Asharf Ali",
    date: "2026-02-13",
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "Gaber Mokhtar",
    date: "2026-02-14",
  },
  {
    id: 9,
    subject: "Physics",
    class: "7A",
    teacher: "Lara Essam",
    date: "2026-02-15",
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "8A",
    teacher: "Bahnasy Wael",
    date: "2026-02-16",
  },
];

export const assignmentsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "Bahnasy Wael ",
    dueDate: "2026-01-30",
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "Lara Essam",
    dueDate: "2026-01-31",
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "Ashraf Mokhtar",
    dueDate: "2026-02-01",
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "Tarek Ali",
    dueDate: "2026-02-02",
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "Badr Shakr",
    dueDate: "2026-02-03",
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "Youmna Mustafa",
    dueDate: "2026-02-04",
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "Ayan Mohsen",
    dueDate: "2026-02-05",
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "Sara Ali",
    dueDate: "2026-02-06",
  },
  {
    id: 9,
    subject: "Physics",
    class: "7A",
    teacher: "Fares Idrees",
    dueDate: "2026-02-07",
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "8A",
    teacher: "Hanan Rizk",
    dueDate: "2026-02-08",
  },
];

export const resultsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "Hanan Rizk",
    student: "Mawada Alaa",
    date: "2026-03-01",
    type: "exam",
    score: 90,
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "Ali Mohammed",
    student: "Lara Sayaed",
    date: "2026-03-02",
    type: "exam",
    score: 90,
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "Dima Salah",
    student: "Fares Mahmoud",
    date: "2026-03-03",
    type: "exam",
    score: 90,
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "Gaber Ali",
    student: "Khaled Ahmed",
    date: "2026-03-04",
    type: "exam",
    score: 90,
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "Youmna Mustafa",
    student: "Omar Fathy",
    date: "2026-03-05",
    type: "exam",
    score: 90,
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "Hend Medhat",
    student: "Hana Ghaly",
    date: "2026-03-06",
    type: "exam",
    score: 90,
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "Enas Omran",
    student: "Anas Tamer",
    date: "2026-03-07",
    type: "exam",
    score: 90,
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "Habiba Montaser",
    student: "Galal Samy",
    date: "2026-03-08",
    type: "exam",
    score: 90,
  },
  {
    id: 9,
    subject: "Physics",
    class: "7A",
    teacher: "Samer Nashaat",
    student: "Ali Ahmed",
    date: "2026-03-09",
    type: "exam",
    score: 90,
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "8A",
    teacher: "Abeer Yousief",
    student: "Asmaa Samir",
    date: "2026-03-10",
    type: "exam",
    score: 90,
  },
];

export const eventsData = [
  {
    id: 1,
    title: "Lake Trip",
    class: "1A",
    date: "2026-05-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 2,
    title: "Picnic",
    class: "2A",
    date: "2026-05-02",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 3,
    title: "Beach Trip",
    class: "3A",
    date: "2026-05-03",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 4,
    title: "Museum Trip",
    class: "4A",
    date: "2026-05-04",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 5,
    title: "Music Concert",
    class: "5A",
    date: "2026-05-05",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 6,
    title: "Magician Show",
    class: "1B",
    date: "2026-05-06",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 7,
    title: "Lake Trip",
    class: "2B",
    date: "2026-05-07",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 8,
    title: "Cycling Race",
    class: "3B",
    date: "2026-05-08",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 9,
    title: "Art Exhibition",
    class: "4B",
    date: "2026-05-09",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 10,
    title: "Sports Tournament",
    class: "5B",
    date: "2026-05-10",
    startTime: "10:00",
    endTime: "11:00",
  },
];

export const announcementsData = [
  {
    id: 1,
    title: "About 4A Math Test",
    class: "4A",
    date: "2026-04-04",
  },
  {
    id: 2,
    title: "About 3A Math Test",
    class: "3A",
    date: "2026-04-02",
  },
  {
    id: 3,
    title: "About 3B Math Test",
    class: "3B",
    date: "2026-04-03",
  },
  {
    id: 4,
    title: "About 6A Math Test",
    class: "6A",
    date: "2026-04-04",
  },
  {
    id: 5,
    title: "About 8C Math Test",
    class: "8C",
    date: "2026-04-05",
  },
  {
    id: 6,
    title: "About 2A Math Test",
    class: "2A",
    date: "2026-04-06",
  },
  {
    id: 7,
    title: "About 4C Math Test",
    class: "4C",
    date: "2026-04-07",
  },
  {
    id: 8,
    title: "About 4B Math Test",
    class: "4B",
    date: "2026-04-08",
  },
  {
    id: 9,
    title: "About 3C Math Test",
    class: "3C",
    date: "2026-04-09",
  },
  {
    id: 10,
    title: "About 1C Math Test",
    class: "1C",
    date: "2026-04-10",
  },
];



export const calendarEvents = [
  { title: "Math", start: new Date(2025, 7, 12, 8, 0), end: new Date(2025, 7, 12, 9, 0), allDay: false },
  { title: "English", start: new Date(2025, 7, 12, 9, 0), end: new Date(2025, 7, 12, 10, 0), allDay: false },
  { title: "Biology", start: new Date(2025, 7, 12, 10, 0), end: new Date(2025, 7, 12, 10, 45), allDay: false },
  { title: "Physics", start: new Date(2025, 7, 12, 11, 0), end: new Date(2025, 7, 12, 11, 45), allDay: false },
  { title: "Chemistry", start: new Date(2025, 7, 12, 13, 0), end: new Date(2025, 7, 12, 13, 45), allDay: false },
  { title: "History", start: new Date(2025, 7, 12, 14, 0), end: new Date(2025, 7, 12, 14, 45), allDay: false },

  { title: "Math", start: new Date(2025, 7, 13, 8, 0), end: new Date(2025, 7, 13, 8, 45), allDay: false },
  { title: "English", start: new Date(2025, 7, 13, 9, 0), end: new Date(2025, 7, 13, 9, 45), allDay: false },
  { title: "Biology", start: new Date(2025, 7, 13, 10, 0), end: new Date(2025, 7, 13, 10, 45), allDay: false },
  { title: "Physics", start: new Date(2025, 7, 13, 11, 0), end: new Date(2025, 7, 13, 11, 45), allDay: false },
  { title: "Chemistry", start: new Date(2025, 7, 13, 13, 0), end: new Date(2025, 7, 13, 13, 45), allDay: false },
  { title: "History", start: new Date(2025, 7, 13, 14, 0), end: new Date(2025, 7, 13, 14, 45), allDay: false },

  { title: "English", start: new Date(2025, 7, 14, 9, 0), end: new Date(2025, 7, 14, 9, 45), allDay: false },
  { title: "Biology", start: new Date(2025, 7, 14, 10, 0), end: new Date(2025, 7, 14, 10, 45), allDay: false },
  { title: "Physics", start: new Date(2025, 7, 14, 11, 0), end: new Date(2025, 7, 14, 11, 45), allDay: false },
  { title: "History", start: new Date(2025, 7, 14, 14, 0), end: new Date(2025, 7, 14, 14, 45), allDay: false },

  { title: "Math", start: new Date(2025, 7, 15, 8, 0), end: new Date(2025, 7, 15, 8, 45), allDay: false },
  { title: "English", start: new Date(2025, 7, 15, 9, 0), end: new Date(2025, 7, 15, 9, 45), allDay: false },
  { title: "Physics", start: new Date(2025, 7, 15, 11, 0), end: new Date(2025, 7, 15, 11, 45), allDay: false },
  { title: "Chemistry", start: new Date(2025, 7, 15, 13, 0), end: new Date(2025, 7, 15, 13, 45), allDay: false },
  { title: "History", start: new Date(2025, 7, 15, 14, 0), end: new Date(2025, 7, 15, 14, 45), allDay: false },
];
